### PR TITLE
Improved the UI of the admin setting pane.

### PR DESCRIPTION
**Pull request by iPurpl3x**

### CODE REVIEW

**Comment by CDK2020** [comment]
@iPurpl3x can you provide a screenshot?

**Comment by clarkwinkelmann** [comment]
@Charlie we've discussed these changes privately already and I have seen
the screenshots, I can take care of the merge. Unless you want to do it
I'll try to take care of this tomorrow evening.

**Comment by clarkwinkelmann** [comment]
Uh... I'm not sure how to push to this PR's branch from the command line. With the git protocol it says I'm not authorized and via password it says wrong password. Not sure if that's because of 2FA or what...

Anyway I made a few additional changes. You can see my follow up commits here https://github.com/FriendsOfFlarum/masquerade/compare/iPurpl3x-master (I pushed my work branch that's branching off this PR)

@iPurpl3x can you confirm the changes look okay for you ? It's mostly code cosmetics.

The only thing I don't understand is the `transform: translateY(15px);` in the CSS. I can't find what it does, the UI appears to look the same with and without. I removed it on my branch but want to be sure whether it was a good move.

If all is good my branch is ready for merge and tag.

**Comment by clarkwinkelmann** [comment]
For reference, changes introduced via this PR:

On the masquerade admin page:

- Added titles to sections (new translations)
- Changed background and color of components to make them move visible
- Added icon to show open/closed state of field editor

image

**Pull request merged**
